services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - DB_CONNECTION_STRING=/app/data/ascentio.db?_journal_mode=WAL&_busy_timeout=5000&_foreign_keys=ON&_cache_size=10000&_synchronous=NORMAL
      - IS_DEVELOPMENT=true
    volumes:
      - .:/app
      - ascentio-data:/app/data
    ports:
      - "8000:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ascentio


  db-dashboard:
    image: coleifer/sqlite-web:latest
    container_name: db-dashboard
    volumes:
      - ascentio-data:/data
    command: sqlite_web -H 0.0.0.0 -p 8080 /data/ascentio.db
    depends_on:
      - app
    ports:
      - "8080:8080"
    networks:
      - ascentio


networks:
  ascentio:


volumes:
  ascentio-data:
