# ProspecTor User Configuration
#
# This file contains user account configurations that will be synchronized
# with the application database when the scheduler runs the sync-users command.
#
# Usage:
#   - Add users to the 'users' list below
#   - Run: ./scheduler sync-users /path/to/this/config/users.yaml
#
# Security Notes:
#   - Keep this file secure and with restricted permissions
#   - Consider encrypting sensitive information in production environments
#   - Passwords are stored here in plain text but will be hashed in the database

users:
  - username: admin
    password: admin123  # This will be hashed when stored in the database
    email: admin@example.com
    role: admin  # Valid values: admin, standard
    reset_on_next_run: false  # Set to true to force password reset on next sync

  - username: demo
    password: demo123
    email: demo@example.com
    role: standard
    reset_on_next_run: false
    