name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., v1.0.0, latest)'
        required: false
        default: 'latest'
      push_image:
        description: 'Push image to registry'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      build_for_pr:
        description: 'Build image for PR (only use when manually triggered from PR)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'
  push:
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.push_image == 'true' || github.event.inputs.build_for_pr == 'true'))
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=${{ github.event.inputs.tag || 'latest' }},enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.build_for_pr == 'false' }}
          type=raw,value=pr-${{ github.event.number }},enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.build_for_pr == 'true' }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Display build information
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "🚀 Building and pushing Docker image for tag: ${{ github.ref_name }}"
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.build_for_pr }}" == "true" ]]; then
          echo "🔧 Building and pushing Docker image for PR: pr-${{ github.event.number }}"
        else
          echo "🔨 Building Docker image only (no push)"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/prod/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.push_image == 'true' || github.event.inputs.build_for_pr == 'true')) }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Clean up untagged images
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'vega-ai'
        package-type: 'container'
        min-versions-to-keep: 0
        delete-only-untagged-versions: true
