name: Build and Push Cloud Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., v1.0.0-cloud, latest-cloud)'
        required: false
        default: 'latest-cloud'
      push_image:
        description: 'Push image to registry'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    tags: [ 'v*-cloud' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-cloud

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true')
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=${{ github.event.inputs.tag || 'latest-cloud' }},enable=${{ github.event_name == 'workflow_dispatch' }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Display build information
      run: |
        echo "☁️ Building Cloud Mode Docker image"
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "Building and pushing for tag: ${{ github.ref_name }}"
        else
          echo "Building with tag: ${{ github.event.inputs.tag || 'latest-cloud' }}"
        fi

    - name: Build and push Cloud Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/prod/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          CLOUD_MODE=true
          COOKIE_SECURE=true
